# Generated by Django 3.2.10 on 2022-06-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('CODE', models.CharField(max_length=50)),
                ('NAME', models.CharField(max_length=500)),
            ],
        ),
    ]
