# Generated by Django 3.2.10 on 2022-06-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamsApp', '0002_changereq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changereq',
            name='APPROVAL',
            field=models.IntegerField(),
        ),
    ]
