# Generated by Django 3.2.10 on 2022-07-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamsApp', '0003_alter_changereq_approval'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('UEID', models.IntegerField()),
                ('LDAP_USERNAME', models.CharField(max_length=500)),
                ('LOGIN', models.CharField(max_length=500)),
                ('GROUPID', models.IntegerField()),
                ('FIRST_NAME', models.CharField(max_length=500)),
                ('LAST_NAME', models.CharField(max_length=500)),
                ('DISP_NAME', models.CharField(max_length=500)),
                ('SHORT_NAME', models.CharField(max_length=500)),
                ('EMAIL', models.CharField(max_length=500)),
                ('ADMIN', models.IntegerField(default=0)),
            ],
        ),
    ]
