# Generated by Django 3.2.10 on 2022-07-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamsApp', '0004_userdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddGrp',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('UID', models.IntegerField()),
                ('USERNAME', models.CharField(max_length=500)),
                ('GROUP', models.CharField(max_length=500)),
                ('HIDDEN', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ArchiveDb',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('UID', models.IntegerField()),
                ('GROUP', models.CharField(max_length=500)),
                ('START', models.DateField()),
                ('END', models.DateField()),
                ('WOR', models.CharField(max_length=500)),
            ],
        ),
    ]
