# Generated by Django 3.2.10 on 2022-07-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamsApp', '0005_addgrp_archivedb'),
    ]

    operations = [
        migrations.AddField(
            model_name='addgrp',
            name='APPROVAL',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='archivedb',
            name='APPROVAL',
            field=models.IntegerField(default=-1),
        ),
    ]
