# Generated by Django 3.2.10 on 2022-07-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamsApp', '0006_auto_20220719_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedb',
            name='END',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='archivedb',
            name='START',
            field=models.CharField(max_length=500),
        ),
    ]
